let panelLanguage = localStorage.getItem('komicove-moderators-language') === 'en' ? 'en' : 'pt-BR';
const panelEnglish = {
  'Destino automático':'Automatic destination','Informe a versão para ver o destino.':'Enter the version to see the destination.',
  'Horário local. Acesso autenticado, com precisão de aproximadamente um minuto. Leitura offline não é registrada.':'Local time. Authenticated access, accurate to approximately one minute. Offline reading is not recorded.',
  'Muitas tentativas. Aguarde alguns minutos.':'Too many attempts. Wait a few minutes.',
  'Você não tem permissão para realizar esta ação.':'You do not have permission to perform this action.',
  'Administração':'Administration','Acesso seguro da equipe':'Secure team access','Usuário':'User','Senha':'Password','Código 2FA':'2FA code','(se ativado)':'(if enabled)','seu usuário':'your username','Entrar no painel':'Sign in to panel','Entrando…':'Signing in…','Controle de acesso, contas e atividade.':'Access control, accounts and activity.','Sair':'Sign out','Seções administrativas':'Administrative sections','Visão geral':'Overview','Tokens':'Tokens','Contas':'Accounts','Histórico':'History','Contribuidores':'Contributors','Atualizações':'Updates','Idioma':'Language',
  'Novo token de administrador':'New administrator token','Somente uma conta que já seja moderadora poderá usá-lo.':'Only an existing moderator can redeem it.','Usos':'Uses','Validade':'Validity','Unidade':'Unit','dias':'days','horas':'hours','Gerar token':'Generate token','Histórico de tokens':'Token history','Copiar':'Copy','Buscar usuário ou e-mail':'Search username or email','Histórico administrativo':'Administrative history','Últimas 250 ações':'Last 250 actions','Atualizar':'Refresh','Motivo':'Reason','Duração':'Duration','1 hora':'1 hour','1 dia':'1 day','7 dias':'7 days','30 dias':'30 days','Cancelar':'Cancel','Confirmar':'Confirm','Conta':'Account','Fechar':'Close',
  'Token de Contribuidor':'Contributor token','Um resgate por token. Contribuidores não recebem permissões de moderação.':'One redemption per token. Contributors do not receive moderation permissions.','Validade em horas':'Validity in hours','Gerar token de Contribuidor':'Generate Contributor token','Copie agora. O token é exibido apenas uma vez.':'Copy it now. The token is only displayed once.','Histórico de Contribuidores':'Contributor history','Carregar mais':'Load more','Publicar mensagem de atualização':'Publish update message','A mensagem aparece nos apps. GitHub e site são apenas destinos do botão Baixar.':'The message appears in the apps. GitHub and the website are only Download button destinations.','Origem':'Source','Criar manualmente':'Create manually','Importar Release do GitHub':'Import GitHub Release','Repositório oficial':'Official repository','Buscar Releases':'Fetch Releases','Selecione uma Release':'Select a Release','Título':'Title','Versão':'Version','Descrição / changelog (Markdown)':'Description / changelog (Markdown)','Pré-visualizar':'Preview','Destino do botão Baixar':'Download button destination','Site do Komicove':'Komicove website','Link de download no GitHub':'GitHub download link','Publicar nos apps':'Publish to apps','Histórico de atualizações':'Update history','Selecione uma versão para visualizar suas informações.':'Select a version to view its details.','Anterior':'Previous','Próxima':'Next','Mais recente':'Latest','Detectada automaticamente':'Detected automatically','Exibida nos aplicativos':'Shown in apps','Exibir nos aplicativos':'Show in apps',
  'Conectado como':'Signed in as','Este painel exige uma conta moderadora.':'This panel requires a moderator account.','Confira os campos informados.':'Check the form fields.','Sem registro':'No record','Ativas':'Active','Suspensas':'Suspended','Banidas':'Banned','Equipe':'Team','Aguardando análise':'Awaiting review','Tokens ativos':'Active tokens','Válido até':'Valid until','Copiado!':'Copied!','usos':'uses','Expira':'Expires','Revogar':'Revoke','Encerrado':'Closed','Nenhum convite.':'No invitations.','Contribuidor':'Contributor','Moderador':'Moderator','Administrador':'Administrator','Dono':'Owner','Banida':'Banned','Suspensa':'Suspended','Ativa':'Active','conta(s)':'account(s)','Tirar moderador':'Remove moderator','Dar moderador':'Make moderator','Criada em:':'Created:','Último acesso à API:':'Last API access:','Ver detalhes':'View details','Desconectar':'Disconnect','Suspender':'Suspend','Remover punição':'Clear restriction','Banir':'Ban','Excluir':'Delete','Nenhuma conta.':'No accounts.','Alterar cargo':'Change role','Suspender conta':'Suspend account','Banir conta':'Ban account','Desconectar dispositivos':'Disconnect devices','Excluir conta':'Delete account','Alterar':'Change','para':'to','Confirmar ação em':'Confirm action for','Envios':'Submissions','Aprovados':'Approved','Rejeitados':'Rejected','Pendentes':'Pending','Publicações':'Publications','Ações recentes':'Recent actions','Nenhuma publicação.':'No publications.','Nenhuma ação.':'No actions.','por':'by','Cargo alterado':'Role changed','Conta suspensa':'Account suspended','Conta banida':'Account banned','Punição removida':'Restriction cleared','Sessões encerradas':'Sessions closed','Conta excluída':'Account deleted','Convite criado':'Invitation created','Convite revogado':'Invitation revoked',
  'Token de Contribuidor criado':'Contributor token created','Token de Contribuidor revogado':'Contributor token revoked','Token de Contribuidor utilizado':'Contributor token used','Mensagem de atualização publicada':'Update message published','Atualização selecionada para os aplicativos':'Update selected for apps','Disponível':'Available','Utilizado':'Used','Revogado':'Revoked','Expirado':'Expired','Criado por':'Created by','Utilizado por':'Redeemed by','Gerando…':'Generating…','Publicando…':'Publishing…','Buscando Releases…':'Fetching Releases…','Selecione uma Release antes de publicar.':'Select a Release before publishing.','Mensagem publicada nos apps.':'Message published to apps.','Atualização selecionada para os aplicativos.':'Update selected for apps.','Atualização não encontrada.':'Update not found.','Nenhuma atualização publicada.':'No update messages published.','Nenhum token de Contribuidor.':'No Contributor tokens.','Não foi possível copiar. Selecione e copie o token acima.':'Could not copy. Select and copy the token above.','Manual':'Manual','Importada do GitHub':'Imported from GitHub','Destino':'Destination','Baixar':'Download','Sem botão Baixar':'No Download button','Não foi possível consultar as releases do GitHub.':'Could not fetch GitHub releases.','Token não encontrado.':'Token not found.','O token já foi utilizado.':'This token was already used.','Token de Contribuidor inválido, expirado, revogado ou utilizado.':'Invalid, expired, revoked or used Contributor token.','Esta conta já possui um cargo. O token não foi consumido.':'This account already has a role. The token was not consumed.','Repositório não permitido.':'Repository is not allowed.','Informe título, versão e changelog válidos.':'Enter a valid title, version and changelog.','Release não encontrada.':'Release not found.','Erro':'Error'
};
function t(value) { return panelLanguage === 'en' ? (panelEnglish[value] || value) : value; }
function panelLabels(values) { return Object.defineProperties({},Object.fromEntries(Object.entries(values).map(([key,value])=>[key,{enumerable:true,get:()=>t(value)}]))); }
const panelStatic = [];
const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
while(walker.nextNode()) {
  const node=walker.currentNode;
  if(['SCRIPT','STYLE'].includes(node.parentElement.tagName)) continue;
  const key=node.textContent.trim();
  if(panelEnglish[key]) panelStatic.push({node,key,original:node.textContent});
}
for(const element of document.querySelectorAll('[placeholder],[aria-label]')) {
  for(const attribute of ['placeholder','aria-label']) { const key=element.getAttribute(attribute); if(panelEnglish[key]) panelStatic.push({node:element,attribute,key}); }
}
function paintPanelLanguage() {
  document.documentElement.lang=panelLanguage;
  document.getElementById('panelLanguage').value=panelLanguage;
  for(const item of panelStatic) { if(item.attribute)item.node.setAttribute(item.attribute,t(item.key)); else item.node.textContent=item.original.replace(item.key,t(item.key)); }
  for(const element of document.querySelectorAll('[data-message]'))element.textContent=t(element.dataset.message);
}
paintPanelLanguage();
document.getElementById('panelLanguage').onchange=async event=>{
  panelLanguage=event.target.value==='en'?'en':'pt-BR';
  localStorage.setItem('komicove-moderators-language',panelLanguage);paintPanelLanguage();
  if(typeof renderDownloadDestination==='function')renderDownloadDestination();
  if(typeof me!=='undefined'&&me) {
    const tasks=[loadContributors(),loadUpdates()];
    if(['admin','owner'].includes(me.role))tasks.push(loadDashboard(),loadInvites(),loadUsers(),loadAudit());
    await Promise.allSettled(tasks);
  }
};
