package com.lucrazy.panel;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.provider.DocumentsContract;
import android.view.*;
import android.widget.*;
import android.text.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
    private final ExecutorService work=Executors.newSingleThreadExecutor(),images=Executors.newFixedThreadPool(2);
    private final Handler handler=new Handler(Looper.getMainLooper());
    private LibraryStore store;private PanelApi api;private LinearLayout root,body;private TextView banner;
    private String tab="Biblioteca",filter="",collection="";private boolean favorites;private int screen;private volatile boolean dead,busy;
    private static final List<PanelApi.Transfer> transfers=new CopyOnWriteArrayList<>();
    private static final int IMPORT=10,TREE=11,BACKUP=12,RESTORE=13;
    @Override public void onCreate(Bundle state){super.onCreate(state);store=new LibraryStore(this);api=new PanelApi(this);shell();handler.postDelayed(()->{if(!dead)checkAndroidUpdates(true);},1800);if(getIntent().getData()!=null&&Intent.ACTION_VIEW.equals(getIntent().getAction()))importFiles(Collections.singletonList(getIntent().getData()));}
    @Override protected void onResume(){super.onResume();if(body!=null&&(tab.equals("Biblioteca")||tab.equals("Coleções")))showLibrary();}
    private void shell(){root=Ui.column(this);root.setBackgroundColor(Ui.BG);setContentView(root);Ui.insets(this,root);
        LinearLayout head=Ui.row(this);Ui.pad(head,12);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.panel_logo);logo.setContentDescription("PANEL");head.addView(logo,new LinearLayout.LayoutParams(Ui.dp(this,70),Ui.dp(this,60)));TextView name=Ui.title(this,"Sua próxima leitura.",20);head.addView(name,new LinearLayout.LayoutParams(0,-2,1));head.addView(Ui.button(this,"+ HQ",this::pickFiles));root.addView(head);
        banner=Ui.text(this,"",14,Ui.MUTED);banner.setPadding(Ui.dp(this,18),0,Ui.dp(this,18),0);banner.setVisibility(View.GONE);root.addView(banner);
        body=Ui.column(this);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=Ui.row(this);for(String label:new String[]{"Biblioteca","Coleções","Comunidade","Ajustes"}){Button b=Ui.button(this,label,()->{tab=label;collection="";if(label.equals("Biblioteca")||label.equals("Coleções"))showLibrary();else if(label.equals("Comunidade"))showCommunity();else settings();});b.setTextSize(11);b.setPadding(0,0,0,0);nav.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,58),1));}root.addView(nav);showLibrary();}
    private LinearLayout page(String title){screen++;body.removeAllViews();ScrollView scroll=new ScrollView(this);LinearLayout content=Ui.column(this);Ui.pad(content,18);content.addView(Ui.title(this,title,28));if(title.equals("Ajustes")){content.addView(Ui.button(this,"Preferências do leitor",()->ReaderPreferences.show(this,null)));content.addView(Ui.button(this,"Verificar atualizações",this::checkAndroidUpdates));content.addView(Ui.button(this,"Diagnóstico seguro",this::diagnostics));}scroll.addView(content);body.addView(scroll,new LinearLayout.LayoutParams(-1,-1));Ui.enter(content);return content;}
    private void note(String text){banner.setText(text);banner.setVisibility(text.isEmpty()?View.GONE:View.VISIBLE);}
    private void fail(Exception e){if(dead)return;String msg=e.getMessage();new AlertDialog.Builder(this).setTitle("PANEL").setMessage(msg==null?"Não foi possível concluir. Verifique o arquivo ou a conexão.":msg).setPositiveButton("Entendi",null).show();note("");}
    interface Job {void run()throws Exception;}
    private void async(String message,Job job,Runnable done){if(busy){Toast.makeText(this,"Aguarde a operação atual.",Toast.LENGTH_SHORT).show();return;}busy=true;note(message);work.execute(()->{try{job.run();runOnUiThread(()->{busy=false;if(dead)return;note("");if(done!=null)done.run();});}catch(Exception e){runOnUiThread(()->{busy=false;if(!dead)fail(e);});}});}
    private void showLibrary(){LinearLayout content=page(tab.equals("Coleções")?"Coleções":"Biblioteca");
        if(tab.equals("Coleções")&&collection.isEmpty()){TreeSet<String> names=new TreeSet<>();for(LibraryStore.Book b:store.all())if(!b.collection.isEmpty())names.add(b.collection);content.addView(Ui.text(this,"Organize uma HQ mantendo sua capa pressionada.",15,Ui.MUTED));if(names.isEmpty())content.addView(Ui.text(this,"Suas coleções aparecerão aqui.",18,Ui.MUTED));for(String name:names){int count=0;for(LibraryStore.Book b:store.all())if(b.collection.equals(name))count++;content.addView(Ui.button(this,name+" · "+count+" HQs",()->{collection=name;showLibrary();}));}return;}
        if(!collection.isEmpty())content.addView(Ui.text(this,collection,18,Ui.RED));
        EditText search=Ui.input(this,"Buscar na sua biblioteca",false);search.setText(filter);content.addView(search);
        LinearLayout actions=Ui.row(this);actions.addView(Ui.button(this,favorites?"★ Favoritos":"☆ Todos",()->{favorites=!favorites;showLibrary();}),new LinearLayout.LayoutParams(0,-2,1));actions.addView(Ui.button(this,"Importar pasta",this::pickTree),new LinearLayout.LayoutParams(0,-2,1));content.addView(actions);
        GridLayout grid=new GridLayout(this);int columns=getResources().getConfiguration().screenWidthDp>=600?3:2;grid.setColumnCount(columns);content.addView(grid);int ticket=screen;
        Runnable render=()->{grid.removeAllViews();List<LibraryStore.Book> all=store.all();int count=0;for(LibraryStore.Book book:all){if(favorites&&!book.favorite||!collection.isEmpty()&&!book.collection.equals(collection)||!book.title.toLowerCase(Locale.ROOT).contains(filter.toLowerCase(Locale.ROOT)))continue;
            LinearLayout card=Ui.column(this);Ui.pad(card,9);card.setBackground(Ui.shape(Ui.SURFACE,Ui.dp(this,12)));GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(Ui.dp(this,4),Ui.dp(this,7),Ui.dp(this,4),Ui.dp(this,7));card.setLayoutParams(lp);
            ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.FIT_CENTER);cover.setContentDescription("Capa de "+book.title);card.addView(cover,new LinearLayout.LayoutParams(-1,Ui.dp(this,190)));TextView title=Ui.title(this,(book.favorite?"★ ":"")+book.title,15);title.setMaxLines(2);title.setMinHeight(Ui.dp(this,52));card.addView(title);card.addView(Ui.text(this,(book.page>0?"Continuar · ":"")+(book.page+1)+" / "+book.count,12,Ui.MUTED));ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(book.count);bar.setProgress(book.page==0?0:book.page+1);card.addView(bar);card.setOnClickListener(v->open(book));card.setOnLongClickListener(v->{bookMenu(book);return true;});card.setFocusable(true);grid.addView(card);count++;
            images.execute(()->{Bitmap bitmap=BitmapFactory.decodeFile(store.cover(book).getAbsolutePath());runOnUiThread(()->{if(!dead&&screen==ticket)cover.setImageBitmap(bitmap);});});}
            if(count==0){TextView empty=Ui.text(this,all.isEmpty()?"Sua coleção começa aqui.\nToque em + HQ para importar seus arquivos.":"Nenhuma HQ corresponde ao filtro.",17,Ui.MUTED);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.columnSpec=GridLayout.spec(0,columns);lp.width=getResources().getDisplayMetrics().widthPixels-Ui.dp(this,50);empty.setLayoutParams(lp);grid.addView(empty);}};
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){filter=s.toString();render.run();}public void afterTextChanged(Editable e){}});render.run();}
    private void open(LibraryStore.Book book){startActivity(new Intent(this,ReaderActivity.class).putExtra("book",book.id));}
    private void bookMenu(LibraryStore.Book book){String[] options={book.favorite?"Remover favorito":"Favoritar","Definir coleção","Renomear","Publicar na comunidade","Remover do celular"};new AlertDialog.Builder(this).setTitle(book.title).setItems(options,(d,n)->{if(n==0){book.favorite=!book.favorite;book.updated=System.currentTimeMillis()/1000.0;store.save(book);showLibrary();}else if(n==1||n==2){EditText value=Ui.input(this,n==1?"Nome da coleção (vazio remove)":"Título",false);value.setText(n==1?book.collection:book.title);new AlertDialog.Builder(this).setTitle(options[n]).setView(value).setPositiveButton("Salvar",(dd,w)->{String text=value.getText().toString().trim();if(n==1)book.collection=text;else if(!text.isEmpty())book.title=text;store.save(book);showLibrary();}).setNegativeButton("Cancelar",null).show();}else if(n==3)publish(book);else new AlertDialog.Builder(this).setTitle("Remover HQ?").setMessage("A cópia importada no PANEL será apagada. O arquivo original não será alterado.").setPositiveButton("Remover",(dd,w)->{store.remove(book);showLibrary();}).setNegativeButton("Cancelar",null).show();}).show();}
    private void pickFiles(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,IMPORT);}
    private void pickTree(){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE),TREE);}
    private void importFiles(List<Uri> files){async("Importando HQs…",()->{StringBuilder errors=new StringBuilder();int done=0;for(Uri uri:files){try{store.importUri(uri);done++;}catch(Exception e){errors.append(store.name(uri)).append(": ").append(e.getMessage()).append("\n");}}if(errors.length()>0)throw new IOException(done+" importada(s).\n"+errors);},()->{tab="Biblioteca";showLibrary();});}
    private void scanTree(Uri rootUri,Uri directory,List<Uri> found,int depth)throws Exception {if(depth>12||found.size()>500)throw new IOException("Pasta grande demais. Importe até 500 HQs por vez.");Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(rootUri,DocumentsContract.getDocumentId(directory));try(Cursor c=getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE},null,null,null)){if(c==null)return;while(c.moveToNext()){Uri child=DocumentsContract.buildDocumentUriUsingTree(rootUri,c.getString(0));if(DocumentsContract.Document.MIME_TYPE_DIR.equals(c.getString(2)))scanTree(rootUri,child,found,depth+1);else if(BookSource.supported(c.getString(1)))found.add(child);}}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;
        if(request==IMPORT){List<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());importFiles(uris);}
        else if(request==TREE&&data.getData()!=null){Uri tree=data.getData();List<Uri> files=new ArrayList<>();async("Procurando quadrinhos…",()->scanTree(tree,DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree)),files,0),()->importFiles(files));}
        else if(request==BACKUP){async("Salvando backup…",()->{try(OutputStream out=getContentResolver().openOutputStream(data.getData())){if(out==null)throw new IOException("Destino indisponível.");store.exportBackup(out);}},()->Toast.makeText(this,"Backup exportado.",Toast.LENGTH_LONG).show());}
        else if(request==RESTORE){int[] count={0};async("Restaurando backup…",()->{try(InputStream in=getContentResolver().openInputStream(data.getData())){count[0]=store.restoreBackup(in);}},()->Toast.makeText(this,count[0]+" HQs atualizadas. Reimporte os arquivos ausentes antes de restaurar.",Toast.LENGTH_LONG).show());}}
    private void settings(){LinearLayout p=page("Ajustes");p.addView(Ui.text(this,"PANEL Android · "+BuildConfig.VERSION_NAME,16,Ui.RED));p.addView(Ui.text(this,"Sua biblioteca funciona offline. Os arquivos selecionados são copiados para o espaço privado do app.",16,Ui.MUTED));p.addView(Ui.title(this,"Comunidade",20));p.addView(Ui.text(this,"Login, sincronização, Descobrir, envios e moderação estão disponíveis quando você entra na sua conta.",14,Ui.MUTED));p.addView(Ui.title(this,"Backup",20));p.addView(Ui.text(this,"Guarda progresso, favoritos, coleções e marcadores. Os arquivos das HQs não são incluídos.",14,Ui.MUTED));p.addView(Ui.button(this,"Exportar dados de leitura",()->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"panel-android-backup.json"),BACKUP)));p.addView(Ui.button(this,"Restaurar backup Android",()->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE),RESTORE)));p.addView(Ui.title(this,"Sobre os formatos",20));p.addView(Ui.text(this,"CBZ, ZIP, PDF, TAR, CBT, 7Z e CB7. CBR/RAR compatíveis com a biblioteca Junrar; RAR5 e arquivos com senha podem não abrir. No Android não é necessário instalar o 7-Zip do Windows.",14,Ui.MUTED));p.addView(Ui.button(this,"Código e licença",()->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/lucrazy-fn/PANEL-ComicBookReader")))));}
    private void showCommunity(){LinearLayout p=page("Comunidade");if(api.base().isEmpty()){p.addView(Ui.text(this,"Configure sua API em Ajustes para acessar Descobrir, contas e envios. A leitura local já está disponível.",17,Ui.MUTED));p.addView(Ui.button(this,"Configurar servidor",this::settings));return;}
        if(api.signedIn()){p.addView(Ui.text(this,"Olá, "+api.user.optString("display_name",api.user.optString("username"))+" · "+api.user.optString("role"),16,Ui.MUTED));p.addView(Ui.button(this,"Meu perfil",this::profile));p.addView(Ui.button(this,"Notificações",this::notifications));p.addView(Ui.button(this,"Sincronizar progresso e favoritos",this::sync));p.addView(Ui.button(this,"Meus envios",()->catalog(true,false)));if(api.moderator())p.addView(Ui.button(this,"Moderação",()->catalog(false,true)));p.addView(Ui.button(this,"Sair da conta",()->async("Saindo…",()->{try{api.json("POST","/auth/logout",null);}finally{api.clear();}},this::showCommunity)));}
        else {p.addView(Ui.text(this,"Você está no modo convidado.",16,Ui.MUTED));p.addView(Ui.button(this,"Entrar / Criar conta",this::login));}
        p.addView(Ui.button(this,"Descobrir quadrinhos",()->catalog(false,false)));p.addView(Ui.button(this,"Central de downloads",this::downloads));}
    private void login(){LinearLayout fields=Ui.column(this);Ui.pad(fields,20);EditText username=Ui.input(this,"Usuário",false),password=Ui.input(this,"Senha",true),code=Ui.input(this,"Código 2FA (se ativado)",false);code.setInputType(2);fields.addView(username);fields.addView(password);fields.addView(code);new AlertDialog.Builder(this).setTitle("Sua conta PANEL").setView(fields).setPositiveButton("Entrar",(d,w)->async("Entrando…",()->api.authenticate("/auth/login",new JSONObject().put("username",username.getText().toString()).put("password",password.getText().toString()).put("totp_code",code.getText().length()==0?JSONObject.NULL:code.getText().toString())),this::showCommunity)).setNeutralButton("Criar conta",(d,w)->async("Criando conta…",()->api.authenticate("/auth/register",new JSONObject().put("username",username.getText().toString()).put("password",password.getText().toString())),this::showCommunity)).setNegativeButton("Cancelar",null).show();}
    private void profile(){JSONObject[] data={null};async("Carregando perfil…",()->data[0]=(JSONObject)api.json("GET","/account/profile",null),()->{LinearLayout p=page("Meu perfil");JSONObject j=data[0];EditText name=Ui.input(this,"Nome de exibição",false),email=Ui.input(this,"E-mail",false);name.setText(j.optString("display_name"));email.setText(j.isNull("email")?"":j.optString("email"));p.addView(Ui.text(this,"@"+j.optString("username")+" · "+j.optString("role"),15,Ui.MUTED));p.addView(name);p.addView(email);p.addView(Ui.button(this,"Salvar perfil",()->async("Salvando…",()->{JSONObject result=(JSONObject)api.json("PATCH","/account/profile",new JSONObject().put("display_name",name.getText().toString()).put("email",email.getText().length()==0?JSONObject.NULL:email.getText().toString()));api.user=result;},this::showCommunity)));p.addView(Ui.button(this,"Trocar senha",()->{LinearLayout f=Ui.column(this);Ui.pad(f,18);EditText old=Ui.input(this,"Senha atual",true),next=Ui.input(this,"Nova senha",true);f.addView(old);f.addView(next);new AlertDialog.Builder(this).setTitle("Trocar senha").setView(f).setPositiveButton("Salvar",(d,w)->async("Alterando senha…",()->{api.json("POST","/account/password",new JSONObject().put("current_password",old.getText().toString()).put("new_password",next.getText().toString()));api.clear();},this::showCommunity)).setNegativeButton("Cancelar",null).show();}));});}
    private void notifications(){JSONArray[] result={null};async("Buscando notificações…",()->result[0]=(JSONArray)api.json("GET","/account/notifications",null),()->{LinearLayout p=page("Notificações");if(result[0].length()==0)p.addView(Ui.text(this,"Nenhuma notificação por aqui.",16,Ui.MUTED));for(int i=0;i<result[0].length();i++){JSONObject n=result[0].optJSONObject(i);p.addView(Ui.title(this,n.optString("title"),19));p.addView(Ui.text(this,n.optString("message"),15,Ui.MUTED));if(n.isNull("read_at"))p.addView(Ui.button(this,"Marcar como lida",()->async("Atualizando…",()->api.json("POST","/account/notifications/"+n.optString("id")+"/read",null),this::notifications)));}});}
    private void sync(){async("Sincronizando…",()->{JSONArray entries=new JSONArray();for(LibraryStore.Book b:store.all())entries.put(new JSONObject().put("item_key",b.id).put("page",b.page).put("favorite",b.favorite).put("client_updated_at",b.updated));JSONArray remote=(JSONArray)api.json("PUT","/account/library-state",new JSONObject().put("items",entries));for(int i=0;i<remote.length();i++){JSONObject row=remote.getJSONObject(i);LibraryStore.Book b=store.get(row.getString("item_key"));if(b!=null&&row.optDouble("client_updated_at",0)>b.updated){b.page=Math.max(0,Math.min(b.count-1,row.optInt("page")));b.favorite=row.optBoolean("favorite");b.updated=row.optDouble("client_updated_at");store.save(b);}}},()->Toast.makeText(this,"Progresso e favoritos sincronizados.",Toast.LENGTH_LONG).show());}
    private void catalog(boolean mine,boolean moderation){JSONArray[] result={null};async("Carregando catálogo…",()->result[0]=(JSONArray)api.json("GET",moderation?"/moderation/queue":mine?"/publications/mine":"/publications/discovery",null),()->{LinearLayout p=page(moderation?"Moderação":mine?"Meus envios":"Descobrir");int ticket=screen;p.addView(Ui.button(this,"Voltar à comunidade",this::showCommunity));if(result[0].length()==0)p.addView(Ui.text(this,"Nenhuma publicação encontrada.",16,Ui.MUTED));for(int i=0;i<result[0].length();i++){JSONObject item=result[0].optJSONObject(i);LinearLayout card=Ui.column(this);Ui.pad(card,12);card.setBackground(Ui.shape(Ui.SURFACE,Ui.dp(this,10)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,Ui.dp(this,15));p.addView(card,lp);ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.FIT_CENTER);cover.setContentDescription("Capa de "+item.optString("title"));card.addView(cover,new LinearLayout.LayoutParams(-1,Ui.dp(this,180)));card.addView(Ui.title(this,item.optString("title"),21));card.addView(Ui.text(this,item.optString("author")+" · "+item.optString("status","Aprovada"),14,Ui.MUTED));if(!item.optString("description").isEmpty())card.addView(Ui.text(this,item.optString("description"),14,Ui.MUTED));if(item.optBoolean("has_file")){images.execute(()->{try{byte[] bytes=api.bytes("/publications/"+item.optString("publication_id")+"/cover");Bitmap b=BitmapFactory.decodeByteArray(bytes,0,bytes.length);runOnUiThread(()->{if(!dead&&ticket==screen)cover.setImageBitmap(b);});}catch(Exception ignored){}});card.addView(Ui.button(this,moderation?"Baixar para revisar":"Baixar para biblioteca",()->download(item)));}if(mine)card.addView(Ui.button(this,"Remover envio",()->new AlertDialog.Builder(this).setTitle("Remover publicação?").setMessage("A publicação sairá da comunidade. Sua HQ local permanece.").setPositiveButton("Remover",(d,w)->async("Removendo…",()->api.json("DELETE","/publications/"+item.optString("publication_id"),null),()->catalog(true,false))).setNegativeButton("Cancelar",null).show()));else if(api.signedIn()&&!moderation)card.addView(Ui.button(this,"Denunciar",()->report(item)));if(moderation){card.addView(Ui.text(this,item.optString("justification"),14,Ui.MUTED));card.addView(Ui.button(this,"Aprovar / Rejeitar",()->decision(item)));}}});}
    private void download(JSONObject item){PanelApi.Transfer t=new PanelApi.Transfer();t.title=item.optString("title");transfers.add(t);downloads();new Thread(()->{try{api.download("/publications/"+item.optString("publication_id")+"/content",item.optString("original_filename","quadrinho.cbz"),store,t);}catch(Exception e){t.error=e.getMessage()==null?"Falha no download":e.getMessage();}finally{t.finished=true;}}).start();}
    private void downloads(){LinearLayout p=page("Downloads");int ticket=screen;if(transfers.isEmpty())p.addView(Ui.text(this,"Os downloads desta sessão aparecerão aqui. Os concluídos ficam na Biblioteca.",16,Ui.MUTED));for(PanelApi.Transfer t:transfers){p.addView(Ui.title(this,t.title,19));TextView label=Ui.text(this,"",14,Ui.MUTED);p.addView(label);ProgressBar progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);p.addView(progress);LinearLayout actions=Ui.row(this);Button pause=Ui.button(this,t.paused?"Continuar":"Pausar",()->{t.paused=!t.paused;downloads();});actions.addView(pause);Button cancel=Ui.button(this,"Cancelar",()->{t.cancelled=true;t.paused=false;});actions.addView(cancel);p.addView(actions);Runnable update=new Runnable(){public void run(){if(dead||screen!=ticket)return;label.setText(t.finished?(t.error.isEmpty()?"Concluído · disponível na biblioteca":t.error):(t.paused?"Pausado · ":"")+t.received/1024+" KB"+(t.total>0?" / "+t.total/1024+" KB":""));progress.setIndeterminate(t.total<=0&&!t.finished);if(t.total>0)progress.setProgress((int)(t.received*100/t.total));pause.setEnabled(!t.finished);cancel.setEnabled(!t.finished&&!t.cancelled);if(!t.finished)handler.postDelayed(this,500);}};update.run();}}
    private void publish(LibraryStore.Book b){if(!api.signedIn()){Toast.makeText(this,"Entre na sua conta na aba Comunidade.",Toast.LENGTH_LONG).show();return;}if(!b.file.matches(".*\\.(cbz|zip|cbr|rar|pdf)$")){Toast.makeText(this,"Publicação aceita CBZ, ZIP, CBR, RAR e PDF.",Toast.LENGTH_LONG).show();return;}ScrollView scroll=new ScrollView(this);LinearLayout fields=Ui.column(this);Ui.pad(fields,18);EditText title=Ui.input(this,"Título",false),author=Ui.input(this,"Autor",false),series=Ui.input(this,"Série (opcional)",false),chapter=Ui.input(this,"Capítulo (opcional)",false),desc=Ui.input(this,"Descrição",false);title.setText(b.title);chapter.setInputType(2);fields.addView(title);fields.addView(author);fields.addView(series);fields.addView(chapter);fields.addView(desc);CheckBox permission=new CheckBox(this);permission.setText("Sou o autor ou tenho autorização para publicar");fields.addView(permission);scroll.addView(fields);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Publicar na comunidade").setView(scroll).setPositiveButton("Enviar",null).setNegativeButton("Cancelar",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(view->{if(!permission.isChecked()||author.getText().toString().trim().isEmpty()||title.getText().toString().trim().isEmpty()){Toast.makeText(this,"Preencha título, autor e confirme a autorização.",Toast.LENGTH_LONG).show();return;}dialog.dismiss();async("Enviando publicação e arquivo…",()->{JSONObject data=new JSONObject().put("title",title.getText().toString()).put("author",author.getText().toString()).put("description",desc.getText().toString()).put("tags",new JSONArray()).put("file_reference",b.file).put("authorship_declared",false).put("authorization_declared",true).put("series_title",series.getText().length()==0?JSONObject.NULL:series.getText().toString()).put("chapter_number",chapter.getText().length()==0?JSONObject.NULL:Integer.parseInt(chapter.getText().toString()));JSONObject result=(JSONObject)api.json("POST","/publications",data);String id=result.getString("publication_id");try{api.upload(id,store.file(b));}catch(Exception e){throw new IOException("O envio foi criado, mas o arquivo falhou. Remova o envio incompleto em Meus envios e tente novamente. "+e.getMessage());}},()->{tab="Comunidade";catalog(true,false);});}));dialog.show();}
    private void report(JSONObject item){EditText reason=Ui.input(this,"Descreva o problema",false);new AlertDialog.Builder(this).setTitle("Denunciar obra").setView(reason).setPositiveButton("Enviar",(d,w)->async("Enviando denúncia…",()->api.json("POST","/reports",new JSONObject().put("target_type","publication").put("target_id",item.optString("publication_id")).put("reason","other").put("description",reason.getText().toString())),()->Toast.makeText(this,"Denúncia enviada.",Toast.LENGTH_SHORT).show())).setNegativeButton("Cancelar",null).show();}
    private void decision(JSONObject item){EditText reason=Ui.input(this,"Justificativa da decisão",false);new AlertDialog.Builder(this).setTitle(item.optString("title")).setView(reason).setPositiveButton("Aprovar",(d,w)->moderate(item,"approved",reason.getText().toString())).setNegativeButton("Rejeitar",(d,w)->moderate(item,"rejected",reason.getText().toString())).setNeutralButton("Cancelar",null).show();}
    private void moderate(JSONObject item,String decision,String reason){async("Salvando decisão…",()->api.json("POST","/moderation/"+item.optString("record_id")+"/decision",new JSONObject().put("decision",decision).put("reason",reason)),()->catalog(false,true));}
    private void checkAndroidUpdates(){checkAndroidUpdates(false);}
    private void checkAndroidUpdates(boolean silent){
        async("Verificando atualizacoes...",()->{
            JSONObject release=api.checkAndroidUpdate();
            String notes=release.optString("body","");
            java.util.regex.Matcher match=java.util.regex.Pattern.compile("(?im)^[ \\t]*(?:[-*#]+[ \\t]*)?android[ \\t]*(?:version[ \\t]*)?([0-9]+\\.[0-9]+(?:\\.[0-9]+)?)").matcher(notes);
            String tag=match.find()?match.group(1):"";
            if(tag.isEmpty()||!isNewer(tag,BuildConfig.VERSION_NAME)){if(!silent)runOnUiThread(()->Toast.makeText(this,"Voce ja esta usando a versao mais recente.",Toast.LENGTH_SHORT).show());return;}
            runOnUiThread(()->{
                String url=release.optString("html_url","https://github.com/lucrazy-fn/PANEL-ComicBookReader/releases");
                String clean=notes.replaceAll("(?m)^#{1,6}\\s*","").replaceAll("`([^`]*)`","$1").replaceAll("\\*\\*([^*]+)\\*\\*","$1").trim();
                new AlertDialog.Builder(this).setTitle("PANEL Android "+tag+" disponivel").setMessage(clean.isEmpty()?"Novidades e correcoes para o leitor.":clean).setPositiveButton("Baixar",(d,w)->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)))).setNegativeButton("Depois",null).show();
            });
        },null);
    }
    private boolean isNewer(String remote,String current){try{String[] a=remote.split("\\."),b=current.split("\\.");for(int i=0;i<3;i++){int x=i<a.length?Integer.parseInt(a[i].replaceAll("[^0-9].*","")):0,y=i<b.length?Integer.parseInt(b[i].replaceAll("[^0-9].*","")):0;if(x!=y)return x>y;}return false;}catch(Exception e){return false;}}
    private void diagnostics(){String report="PANEL Android "+BuildConfig.VERSION_NAME+"\nAPI configurada: sim\nConta conectada: "+(api.signedIn()?"sim":"não")+"\nDispositivo: "+Build.MANUFACTURER+" "+Build.MODEL+"\nAndroid: "+Build.VERSION.RELEASE+"\nLivros locais: "+store.all().size();new AlertDialog.Builder(this).setTitle("Diagnóstico seguro").setMessage(report).setPositiveButton("Copiar",(d,w)->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("Diagnóstico PANEL",report));Toast.makeText(this,"Diagnóstico copiado sem dados sensíveis.",Toast.LENGTH_SHORT).show();}).setNegativeButton("Fechar",null).show();}
    @Override protected void onDestroy(){dead=true;handler.removeCallbacksAndMessages(null);work.shutdown();images.shutdown();super.onDestroy();}
}
