package com.lucrazy.panel;

import android.content.Context;
import android.graphics.*;
import android.view.*;
import java.util.*;

final class PanelEditorView extends View {
    private final Bitmap image; final ArrayList<RectF> panels=new ArrayList<>(); int selected=-1,mode=0;float sx,sy;RectF original;
    private final Paint bitmapPaint=new Paint(Paint.FILTER_BITMAP_FLAG),line=new Paint(1),fill=new Paint(1);RectF imageBox=new RectF();
    PanelEditorView(Context c,Bitmap bitmap,java.util.List<RectF> source){super(c);image=bitmap;for(RectF r:source)panels.add(new RectF(r));line.setStyle(Paint.Style.STROKE);line.setStrokeWidth(Ui.dp(c,3));fill.setTextSize(Ui.dp(c,16));fill.setColor(Color.WHITE);setMinimumHeight(Ui.dp(c,440));}
    protected void onDraw(Canvas c){super.onDraw(c);float scale=Math.min(getWidth()/(float)image.getWidth(),getHeight()/(float)image.getHeight());float w=image.getWidth()*scale,h=image.getHeight()*scale;imageBox.set((getWidth()-w)/2,(getHeight()-h)/2,(getWidth()+w)/2,(getHeight()+h)/2);c.drawColor(Color.rgb(8,8,14));c.drawBitmap(image,null,imageBox,bitmapPaint);for(int i=0;i<panels.size();i++){RectF r=screen(panels.get(i));line.setColor(i==selected?Ui.RED:0xff52d6ff);c.drawRect(r,line);c.drawText(String.valueOf(i+1),r.left+8,r.top+20,fill);if(i==selected){Paint p=new Paint();p.setColor(Ui.RED);for(float[] q:new float[][]{{r.left,r.top},{r.right,r.top},{r.left,r.bottom},{r.right,r.bottom}})c.drawCircle(q[0],q[1],Ui.dp(getContext(),7),p);}}}
    private RectF screen(RectF r){return new RectF(imageBox.left+r.left*imageBox.width(),imageBox.top+r.top*imageBox.height(),imageBox.left+r.right*imageBox.width(),imageBox.top+r.bottom*imageBox.height());}
    private float nx(float x){return Math.max(0,Math.min(1,(x-imageBox.left)/imageBox.width()));}private float ny(float y){return Math.max(0,Math.min(1,(y-imageBox.top)/imageBox.height()));}
    public boolean onTouchEvent(android.view.MotionEvent e){float x=nx(e.getX()),y=ny(e.getY());if(e.getAction()==MotionEvent.ACTION_DOWN){sx=x;sy=y;selected=-1;mode=1;for(int i=panels.size()-1;i>=0;i--){RectF r=panels.get(i);if(r.contains(x,y)){selected=i;original=new RectF(r);mode=2;float m=.04f;if(Math.abs(x-r.left)<m&&Math.abs(y-r.top)<m)mode=3;else if(Math.abs(x-r.right)<m&&Math.abs(y-r.top)<m)mode=4;else if(Math.abs(x-r.left)<m&&Math.abs(y-r.bottom)<m)mode=5;else if(Math.abs(x-r.right)<m&&Math.abs(y-r.bottom)<m)mode=6;break;}}invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){if(mode==1){panels.add(new RectF(Math.min(sx,x),Math.min(sy,y),Math.max(sx,x),Math.max(sy,y)));selected=panels.size()-1;mode=7;}else if(mode==7)panels.set(selected,new RectF(Math.min(sx,x),Math.min(sy,y),Math.max(sx,x),Math.max(sy,y)));else if(selected>=0){RectF r=new RectF(original);if(mode==2){float dx=x-sx,dy=y-sy;dx=Math.max(-r.left,Math.min(1-r.right,dx));dy=Math.max(-r.top,Math.min(1-r.bottom,dy));r.offset(dx,dy);}else{if(mode==3||mode==5)r.left=Math.min(x,r.right-.02f);if(mode==4||mode==6)r.right=Math.max(x,r.left+.02f);if(mode==3||mode==4)r.top=Math.min(y,r.bottom-.02f);if(mode==5||mode==6)r.bottom=Math.max(y,r.top+.02f);}panels.set(selected,r);}invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(selected>=0&&panels.get(selected).width()<.02f)panels.remove(selected);mode=0;invalidate();return true;}return true;}
    void deleteSelected(){if(selected>=0){panels.remove(selected);selected=-1;invalidate();}}void reorder(int d){if(selected<0)return;int n=Math.max(0,Math.min(panels.size()-1,selected+d));Collections.swap(panels,selected,n);selected=n;invalidate();}
}
