
TEXTS = {
    "en": {"library":"Library","collections":"Collections","theme":"Theme","fit":"⊞ Fit","fullscreen":"⛶ Fullscreen","language":"Choose Language","choose_library_folder":"Choose Library Folder","error":"Error","back":"← Back","no_comics":"No comics found","add_folder":"Choose a folder","light":"Light Mode","dark":"Dark Mode","folder":"Folder","manga_off":"🇯🇵 Manga OFF","manga_on":"🇯🇵 Manga ON","no_collections":"No collections found","issues":"issue","back_collections":"← Collections","all":"All","subfolders":"Folders","series":"Series","sort_name":"Name","sort_date":"Date","sort_progress":"Progress","read":"read","continue_reading":"▶ Continue","sort_by":"Sort:","unread":"Unread","search":"Search…","no_results":"No results for","loading":"Loading…","continue_section":"Continue Reading","next_issue":"Next issue","next_chapter_q":"Next issue of the series?","yes":"Yes","no":"No","bookmark":"Bookmark","immersive":"Immersive","rotate":"Rotate","brightness":"Brightness","double_page":"Double Page","filter_status":"Status","f_all":"All","f_unread":"Unread","f_reading":"Reading","f_done":"Done"},
    "pt": {"library":"Biblioteca","collections":"Coleções","theme":"Tema","fit":"⊞ Encaixar","fullscreen":"⛶ Tela Cheia","language":"Escolha o Idioma","choose_library_folder":"Escolher Pasta","error":"Erro","back":"← Voltar","no_comics":"Nenhuma história encontrada","add_folder":"Escolher pasta","light":"Modo Claro","dark":"Modo Escuro","folder":"Pasta","manga_off":"🇯🇵 Mangá OFF","manga_on":"🇯🇵 Mangá ON","no_collections":"Nenhuma coleção encontrada","issues":"edição","back_collections":"← Coleções","all":"Todas","subfolders":"Pastas","series":"Séries","sort_name":"Nome","sort_date":"Data","sort_progress":"Progresso","read":"lidas","continue_reading":"▶ Continuar","sort_by":"Ordenar:","unread":"Não lido","search":"Buscar…","no_results":"Nenhum resultado para","loading":"Carregando…","continue_section":"Continuar Lendo","next_issue":"Próxima edição","next_chapter_q":"Próxima edição da série?","yes":"Sim","no":"Não","bookmark":"Marcador","immersive":"Imersivo","rotate":"Girar","brightness":"Brilho","double_page":"Página Dupla","filter_status":"Status","f_all":"Todos","f_unread":"Não lidos","f_reading":"Lendo","f_done":"Concluídos"},
}




from komicove_app.design.colors import DARK, LIGHT
